CHANGELOG.md, vic.api.v0.yaml, vic.api.v1.yaml
* Adds `description` to the `V0` `Vendor` object.
* Replaces `TaxInfoUs`, `TaxInfoSe`, and `TaxInfoNo` with a simplified `VendorTaxInfo` model.
* Bumps schema version to `v0.3.15`
=> chore: Update Vendor documentation

vic.api.v0.yaml
Fixes invoice line item VAT descriptions and other descriptions for some fields.
=> docs: Fix the Invoice line item VAT descriptions

vic.api.v0.yaml
these duplacate fields were preventing import of the spec to Postman
=> fix(public-api): :fire: remove duplicate fields

CHANGELOG.md, vic.api.v0.yaml
This was requested to set a formal pattern on the cost account's number field to only support digits.
We are planning to support alphanumeric in the future, but we have no ETA on that.
=> fix: Set cost account number field to follow a numeric pattern.

vic.api.v0.yaml, vic.api.v1.yaml
Clarification that `ExternalId` can be any non empty string.
=> docs: Fix ExternalId schema description

CHANGELOG.md, vic.api.v0.yaml, vic.api.v1.yaml
These fields were specified but never mapped into anything. We do not currently support dimensions with parents and cost accounts with required dimensions being specified.
=> fix: Remove unsupported fields from V0 Dimension and Account schemas

CHANGELOG.md, scripts/openapi-build.py, vic.api.v0.yaml, vic.api.v1.yaml
The goal here is to compact each of the request definitions down some and provide for easy named references for response objects.
- Lift all error responses to the `#/components/responses` section.
- Replace `obtainToken` response with `#/components/responses/TokenCreatedResponse`
- Replace `healthCheck` response with `#/components/responses/HealthyResponse`
- Replace `listAccounts` response with `#/components/responses/AccountsResponse`
- Replace `getAccount` response with `#/components/responses/AccountResponse`
- Replace `upsertAccount` response with `#/components/responses/AccountUpsertedResponse`
- Replace `deleteAccount` response with `#/components/responses/AccountDeletedResponse`
- Replace `listDimensions` response with `#/components/responses/DimensionsResponse`
- Replace …
=> refactor: Make responses re-usable for errors

CHANGELOG.md, vic.api.v0.yaml
We will still support the singularized name until at least end of August. But after that, they will be removed completely.
=> feat: Rename singular resource name to pluralized name

CHANGELOG.md, vic.api.v0.yaml
* Adds the `typeExternalId` to `DimensionUpsert` and `Dimension` schemas.
* Sets max length for inputs for `type` and `name`.
* Mark `name` as required.
=> feat: Add `typeExternalId` to `DimensionUpsert` and `Dimension` schemas

CHANGELOG.md, vic.api.v0.yaml
These two callbacks will have the same payload.
=> feat: `invoiceTransfer` callback will now receive the same payload as `invoicePost`

CHANGELOG.md, vic.api.v0.yaml
This allows negative values for the following fields
* `quantityRequested` 
* `quantityReceived`
* `quantityInvoiced`
* `unitAmount`
* `lineItemTotal`.
=> fix: Allow negative values for purchase orders

vic.api.v0.yaml
Fixing things I find while working on `DERP` purchase orders
- `lineItems` seems to be a required field when creating purchase order
=> fix: misc corrections

CHANGELOG.md, vic.api.v0.yaml
- Replaced `bolNumber` with `bolNumbers` for `#/components/schemas/Invoice`.
- Replaced `bolNumber` with `bolNumbers` for `#/components/schemas/TrainingInvoice`.
- Replaced `bolNumber` with `bolNumbers` for `#/components/schemas/CreateInvoice`.
- Replaced `bolNumber` with `bolNumbers` for `#/components/schemas/TrainingInvoiceUpsert`.
- Added `typeName` to `#/components/schemas/Dimension`.
- Added `typeName` to `#/components/schemas/DimensionUpsert`.
- Added support for managing payment terms.
closes #53
=> Add bill of lading and type name for dimensions

vic.api.v0.yaml
- Add `Invoice.fields`
- Add `CreateInvoice.fields`
- Add `TrainingInvoice.fields`
- Add `TrainingInvoiceUpsert.fields`
=> feat(custom_fields): Add custom fields support to `Invoice` and `TrainingInvoice`

.tool-versions
```bash
~/v/api-docs  chore-nodejs-21.6.2  asdf install nodejs 21.7.1                      
Trying to update node-build... ok
node-build: definition not found: 21.7.1
```
=> chore: nodejs 21.6.2

docs/attachments.md, vic.api.v0.yaml
Move attachments content to markdown file
=> Attachments markdown

CHANGELOG.md, vic.api.v0.yaml
- Add `number` to `#/components/schemas/CreateInvoiceLineItem`
- Add `number` to `#/components/schemas/InvoiceLineItem`
- Add `number` to `#/components/schemas/TrainingInvoiceLineItemUpsert`
- Add `unitPrice` to `#/components/schemas/CreateInvoiceLineItem`
- Add `unitPrice` to `#/components/schemas/TrainingInvoiceLineItemUpsert`
=> feat: Add `number` and `unitPrice` to invoice items

CHANGELOG.md, vic.api.v0.yaml
Document `taxCodeId` on `TrainingInvoiceLineItemUpsert`. I think this was the last missing tax code documentation.
=> feat: Add `taxCodeId` to `TrainingInvoiceLineItemUpsert`

CHANGELOG.md, docs/synchronizing.md, vic.api.v0.yaml
- Add `POST - /v0/accounts/synchronize` to synchronize GL Accounts.
- Add `POST - /v0/dimensions/synchronize` to synchronize Dimensions.
- Add `POST - /v0/paymentTerms/synchronize` to synchronize Payment Terms.
- Add `POST - /v0/purchaseOrders/synchronize` to synchronize Purchase Orders.
- Add `POST - /v0/vatCodes/synchronize` to synchronize Vat Codes.
- Add `POST - /v0/vendors/synchronize` to synchronize Vendors.
=> feat: Add ability to trigger resource synchronization

CHANGELOG.md, vic.api.v0.yaml
* Get a payment term using internal id or external id.
* Update a payment term using internal id or external id.
* Update a payment term's external id.
* Delete a payment term using internal id or external id.
* Create a payment with an external id. Upsert is not implemented, nor will it be.
=> feat: Add ability to retrieve payment terms using external id

CHANGELOG.md, vic.api.v0.yaml
Documents the following abilities:
* Get a purchase order by `externalId`.
* Delete a purchase order by `externalId`.
* Update a purchase order by `externalId`.
* Get a purchase order item by `externalId`.
* Delete a purchase order item by `externalId`.
* Update a purchase order item by `externalId`.
=> feat: Add ability to manage Purchase Orders using external id
