- CHANGELOG.md
- vic.api.v0.yaml
Removed api information from vic-api and adding them here
> feat: Adds documentation for invoice confirmation

- CHANGELOG.md
- vic.api.v1.yaml
Adds documentation for the v1 purchase orders. Feel free to suggest more information or point out any grammatical errors.
> feat: Add documentation for v1 purchase orders

- CHANGELOG.md
- vic.api.v0.yaml
- vic.api.v1.yaml
Adding what I could find from purchase order input and purchase order line item input.
> chore: document po create and get

- CHANGELOG.md
- vic.api.v0.yaml
This adds documentation for the upcoming `getSubscription` operation
> feat: Add `getSubscription` v0 operation

- CHANGELOG.md
- vic.api.v0.yaml
Alpha group requested these on the return, already added to api
> docs: :memo: return custom fields list of custom fields

- CHANGELOG.md
- vic.api.v1.yaml
removing double documentation so the spec is valid.
> docs: :bug: double documentation for purchase orders

- src/v0/invoices/README.md
Using the format of training invoices.
ENG-2029
> docs(public_api): :memo: first draft of invoice documentation

- CHANGELOG.md
- vic.api.v0.yaml
- vic.api.v1.yaml
This adds more fields for the dimension object attached to invoice and training invoice line items.
> feat: Expand dimension definition for invoice items

- CHANGELOG.md
- vic.api.v0.yaml
Adds documentation for the `createDimension` operation.
> feat: Add `createDimension` api operation

- CHANGELOG.md
- src/v0/purchase_orders/README.md
- vic.api.v0.yaml
Adds the following:
* `createPurchaseOrderLineItem`
* `updatePurchaseOrderLineItem`
* `deletePurchaseOrderLineItem`
* `updatePurchaseOrder`
* More supplemental documentation for purchase order updates.
> feat: Adds Purchase Order Manipulation documentation

- CHANGELOG.md
- vic.api.v0.yaml
Adds support for BOL number through public api
> feat: Bill of lading number

- CHANGELOG.md
- src/v0/purchase_orders/README.md
- vic.api.v0.yaml
Added `requestor` object to `purchaseOrders`
> feat: `requestor` when creating or updating a PO

- CHANGELOG.md
- vic.api.v0.yaml
For https://vicaiglobal.atlassian.net/browse/ENG-4409
> feat: Tags and Vendor Tags

- CHANGELOG.md
- vic.api.v0.yaml
Allows non numeric values to be passed for cost account numbers
> feat: Allow non-numeric numbers for cost accounts

- vic.api.v0.yaml
https://github.com/Vic-ai/vic-api/pull/7762
https://vicaiglobal.atlassian.net/browse/ENG-5486
> feat(tax_handling): Adds Self-assessed use tax fields to Invoice object

- src/SUMMARY.md
- src/v0/vendor_groups/README.md
- vic.api.v0.yaml
Adds documentation for vendor groups.
> feat: Add vendor group documentation

- vic.api.v0.yaml
https://vicaiglobal.atlassian.net/browse/ENG-5766
> feat: Add invoice amount fields

- vic.api.v0.yaml
https://vicaiglobal.atlassian.net/browse/ENG-6279
> chore(doc): Set `CreateInvoiceLineItem.issuedOn` field as non-nullable

- vic.api.v0.yaml
https://vicaiglobal.atlassian.net/browse/ENG-6632
https://github.com/Vic-ai/vic-api/pull/8006
> chore: Add `refNumber` to `TrainingInvoiceUpsert` required fields

- vic.api.v0.yaml
Adds listing purchase order operation
> GET /v0/purchaseOrders

- Makefile
- requirements.txt
- vic.api.v0.yaml
This is so we can maintain consistent formatted docs and make sure future docs added adhere to it.
> chore: Enforce yaml formatting with yamlfix

- CHANGELOG.md
- src/SUMMARY.md
- src/v0/payments.md
- src/v0/webhooks.md
- vic.api.v0.yaml
* Adds the ability to list payment batches.
* Adds the ability to subscribe to payment batch processed events.
* Adds new webhook events end points.
> feat: Add payments module documentation

- vic.api.v0.yaml
> feat: Add invoice and item `amountTax` fields

- CHANGELOG.md
- vic.api.v0.yaml
> feat: Update POST /invoices

- CHANGELOG.md
- vic.api.v0.yaml
JIRA: https://vicaiglobal.atlassian.net/browse/ENG-8159
Related PR: https://github.com/Vic-ai/vic-api/pull/8494
> feat: Add `vatRate` to `InvoiceLineItemInfo`

- CHANGELOG.md
- vic.api.v0.yaml
Fixes incorrect documentation for invoice item amounts and vat amounts.
> fix: Incorrect line item amount description for invoices

- CHANGELOG.md
- vic.api.v0.yaml
- Add `totalAmount` to `#/components/schemas/CreateInvoice`
- Add `totalAmount` to `#/components/schemas/TrainingInvoiceUpsert`
> feat: Add totalAmount to CreateInvoice

- vic.api.v0.yaml
Implemented in https://github.com/Vic-ai/vic-api/pull/8739 and https://github.com/Vic-ai/vic-api/pull/8758
> feat: Attachment uploads

- docs/main.md
- vic.api.v0.yaml
Should close https://github.com/Vic-ai/api-docs/issues/4
> chore: Tweak main page copy + Pagination section

- redocly.yaml
- vic.api.v0.yaml
Just to make the main page a little cleaner 🤓
> chore: Hide "License MIT" and "Download Open API" button"

- Makefile
- docs/authentication.md
- docs/main.md
- docs/pagination.md
- index.hbs
- redocly.yaml
- vic.api.v0.yaml
* Uses custom template for building HTML. Didnt find any other way to add meta tags for nice sharing-links and support better SEO.
* Changes text for main page.
* Changes text for Getting started.
* Changes text for pagination.
* Changes text for authentication.
* Hides annoying loading screen that blickers slightly atm.
* Reorganizes sidebar menu so Authentication comes right after Getting started.
> chore: Some tweaks

- redocly.yaml
This download button is really nice for working with postman. I wasnt aware 🤷‍♂️
> chore: re-add download link

- docs/attachments.md
> chore: add note on attachment mime codes + hide Svefakt support for now

- CHANGELOG.md
- Makefile
- vic.api.v0.yaml
This adds documentation for the new vendor look up methods
> feat: Adds new vendor lookup methods

- docs/create_purchase_order_line_item.md
Added information about changing Purchase Order status from `closed` to `open` when new Purchase Order Line Item is created.
> chore: Add info about changing PO status when creating new PO line item

- CHANGELOG.md
- docs/create_purchase_order.md
- vic.api.v0.yaml
https://vicaiglobal.atlassian.net/browse/ENG-10665
> feat: Add siteOwner to Purchase Order

- CHANGELOG.md
- vic.api.v0.yaml
Add `amountTax` to `#/components/schemas/TrainingInvoiceLineItemUpsert`
> feat: Add `amountTax` to `TrainingInvoiceLineItemUpsert`

- CHANGELOG.md
- vic.api.v0.yaml
https://vicaiglobal.atlassian.net/browse/ENG-5653
> feat: Add `taxCode` to `InvoiceLineItem`

- CHANGELOG.md
- vic.api.v0.yaml
Adds `acceptedAt` to `Payment` and `Credit` objects.
> feat: Add `acceptedAt` for payments

- CHANGELOG.md
- vic.api.v0.yaml
- Add `markedAS` and `billStatus` in Invoice
- Add `MarkedAsFilter` and `BillStatusFilter` in list Invoice
> feat: Add `markedAs` and `billStatus` to `#/components/schemas/Invoice`
